server:
  port: 9001
  
spring:
  application:
    name: SEARCH-FLIGHTS-SERVICE
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost